"""migracios en mienbros aumento el numero de telefono

Revision ID: e43293ee655b
Revises: 5d4c9e03773b
Create Date: 2026-05-26 17:22:40.872502

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e43293ee655b'
down_revision = '5d4c9e03773b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('miembros', schema=None) as batch_op:
        batch_op.add_column(sa.Column('telefono', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('miembros', schema=None) as batch_op:
        batch_op.drop_column('telefono')

    # ### end Alembic commands ###
